import chai: expect
import supertest as supertest
import redis
import bluebird

import ../app
import ../config

client = bluebird.promisifyAll(redis.createClient())
request = bluebird.promisifyAll(supertest)


describe('Express server', () ->
  beforeEach(() ->
    config.FRIGG_WORKER_VERSION = null
    config.FRIGG_COMMON_VERSION = null
    config.FRIGG_COVERAGE_VERSION = null

    return client
      .selectAsync(2)
      .then(() -> client.delAsync('frigg:queue'))
  )

  describe('/*', () ->
    it('should redirect to frigg.io', () ->
      return request(app)
        .get('/')
        .expectAsync(302)
    )
  )

  describe('/fetch', () ->
    it('should return 403 without token', () ->
      return request(app)
        .get('/fetch')
        .expectAsync(403)
    )

    it('should return 200 if there is no job', () ->
      return request(app)
        .get('/fetch')
        .set('x-frigg-worker-token', 'token')
        .expect(200)
        .endAsync()
        .then((res) ->
          expect(res.body.job).to.equal(null)
        )
    )

    it('should deny access from old worker (worker)', () ->
      config.FRIGG_WORKER_VERSION = '1.0.0'
      return request(app)
        .get('/fetch')
        .set('x-frigg-worker-token', 'token')
        .expect(400)
        .endAsync()
        .then((res) ->
          expect(res.body.error).to.equal('Outdated worker')
        )
    )

    it('should deny access from old worker (common)', () ->
      config.FRIGG_COMMON_VERSION = '1.0.0'
      return request(app)
        .get('/fetch')
        .set('x-frigg-worker-token', 'token')
        .expect(400)
        .endAsync()
        .then((res) ->
          expect(res.body.error).to.equal('Outdated worker')
        )
    )

    it('should deny access from old worker (coverage)', () ->
      config.FRIGG_COVERAGE_VERSION = '1.0.0'
      return request(app)
        .get('/fetch')
        .set('x-frigg-worker-token', 'token')
        .expect(400)
        .endAsync()
        .then((res) ->
          expect(res.body.error).to.equal('Outdated worker')
        )
    )

    it('should return job', () ->
      jobObj = { branch: 'master' clone_url: 'url' }
      return client
        .selectAsync(2)
        .then(() -> client.lpushAsync('frigg:queue', JSON.stringify(jobObj)))
        .then(() ->
          return request(app)
            .get('/fetch')
            .set('x-frigg-worker-token', 'token')
            .expect(200)
            .endAsync()
        )
        .then((res) ->
          expect(res.body.job.branch).to.equal('master')
          expect(res.body.job.clone_url).to.equal('url')
        )
    )

    it('should return job from custom queue', () ->
      jobObj = { branch: 'master' clone_url: 'url-custom' }
      return client
        .selectAsync(2)
        .then(() -> client.lpushAsync('frigg:queue:custom', JSON.stringify(jobObj)))
        .then(() ->
          return request(app)
            .get('/fetch/custom')
            .set('x-frigg-worker-token', 'token')
            .expect(200)
            .endAsync()
        )
        .then((res) ->
          expect(res.body.job.branch).to.equal('master')
          expect(res.body.job.clone_url).to.equal('url-custom')
        )
    )
  )
)
