import express
import redis

export app

client = redis.createClient(
  process.env.REDIS_PORT or 6379,
  process.env.REDIS_HOST or '127.0.0.1'
)

app = express()

app.get('/fetch', (req, res) ->
  if req.headers['x-frigg-worker-token'] != process.env.FRIGG_WORKER_TOKEN
    return res.status(403).json({ error: 'Missing token'})

  client.select(2, () ->
    client.rpop('frigg:queue', (err, result) ->
      if err
        throw err

      return res.json({ job: JSON.parse(result) })
    )
  )
)
